#-----------------------------------------------------------------------------
# Code 1: PCA and Visualization of Logit-transformed Ecoregion Trait Proportions (Fig 1a, 1b)
#
# Description:
# This script performs PCA analysis and visualization based on the Logit-transformed 
# data processed by Supplementary Code 1:
# 1. Reads Trait_Logit_Proportion_Ecoregion_No_Imputation_30Greater.csv.
# 2. Performs PCA analysis.
# 3. Saves PCA results (including metadata and PC1-PC15 scores):
#     PCA_std_Trait_Logit_Proportion_Ecoregion_No_Imputation.csv
# 4. Plots PCA Biplot (Fig1_a):
#     - Includes Biome color mapping.
#     - Includes Species Number size mapping.
#     - Includes arrows for positive traits (solid) and opposite traits (dashed).
# 5. Plots Variable Contribution (Fig1_b):
#     - Displays the contribution of each trait to PC1, PC2, and PC3.
# 6. Saves visualization results as PDF files.
#
# Data:
# Input file is generated by Supplementary Code 1:
# Trait_Logit_Proportion_Ecoregion_No_Imputation_30Greater.csv
# Data applying the full GBIF distribution are provided in the repository.
#
# Last Update: 2026/02/06
#-----------------------------------------------------------------------------

# 1. Set Working Directory and Load Libraries
#-----------------------------------------------------------------------------
setwd("F:/GitHub/ZhangChunyu-GeoBio/Angiosperm-Biogeographical-Spectrum/Data")

library(data.table)
library(factoextra)
library(ggplot2)
library(tidyr)
library(dplyr)

# 2. Parameter Settings
#-----------------------------------------------------------------------------
# --- File Paths ---
input_data_path  <- "Trait_Logit_Proportion_Ecoregion_No_Imputation_30Greater.csv"
output_pca_data  <- "PCA_std_Trait_Logit_Proportion_Ecoregion_No_Imputation.csv"
output_pdf_a     <- "Fig1_a.pdf"
output_pdf_b     <- "Fig1_b.pdf"

# --- PCA Variable List (Must match input file column names) ---
pca_vars <- c(
  "GF_H", "LC_A", "PH_D", "RS_T", "PT_U", "LS_C", "LM_L", "LV_P",
  "SS_B", "IF_I", "OP_H", "FS_Z", "PF_C", "FT_D", "FD_D"
)

# --- Visual Parameters: Biome Colors ---
biome_colors <- c(
  "Trop/Subtrop Forests" = "#247713",
  "Temp Forests"         = "#8DBC50",
  "Boreal Taiga"         = "#7695CC",
  "Grasslands"           = "#EDEA96",
  "Tundra"               = "#3B5FAB",
  "Mediterranean Scrub"  = "#D17EAC",
  "Deserts & Drylands"   = "#A50E60"
)

# --- Visual Parameters: Opposite Trait Mapping (for Biplot arrows) ---
trait_map <- c(
  "GF_H" = "GF_W", "LC_A" = "LC_P", "PH_D" = "PH_E", 
  "RS_T" = "RS_F", "PT_U" = "PT_M", "LS_C" = "LS_S", 
  "LM_L" = "LM_E", "LV_P" = "LV_R", "SS_B" = "SS_U", 
  "IF_I" = "IF_D", "OP_H" = "OP_E", "FS_Z" = "FS_A", 
  "PF_C" = "PF_S", "FT_D" = "FT_F", "FD_D" = "FD_I"
)

# --- Visual Parameters: Styling Details ---
pc2_display_range <- c(-5, 5)        # Y-axis display range
line_width_custom <- 0.3             # Arrow line width
arrow_tip_length  <- unit(0.3, "cm") # Arrow tip length
dash_pattern      <- "84"            # Dashed line pattern


# 3. Data Loading and Preprocessing
#-----------------------------------------------------------------------------
cat("Loading data...\n")
df_traits <- fread(input_data_path)

# Remove NA values (if any)
df_pca <- na.omit(df_traits)
cat(sprintf(" -> Analysis includes %d ecoregions.\n", nrow(df_pca)))

# --- Create Species Count Categories (SizeCategory) ---
# Use SpeciesNumber column for quantile splitting
quartiles <- quantile(df_pca$SpeciesNumber, probs = seq(0, 1, length.out = 4))
breaks <- unique(quartiles)

custom_labels <- vapply(1:(length(breaks) - 1), function(i) {
  lower <- format(round(breaks[i]), scientific = FALSE, trim = TRUE)
  upper <- format(round(breaks[i+1]), scientific = FALSE, trim = TRUE)
  if (i == 1) {
    return(paste0("[", lower, ", ", upper, "]"))
  } else {
    return(paste0("(", lower, ", ", upper, "]"))
  }
}, FUN.VALUE = character(1))

df_pca$SizeCategory <- cut(
  df_pca$SpeciesNumber,
  breaks = breaks,
  include.lowest = TRUE,
  labels = custom_labels
)


# 4. Perform PCA Analysis
#-----------------------------------------------------------------------------
cat("Performing PCA analysis...\n")
# Perform PCA only on numeric trait columns
pca_result <- prcomp(df_pca[, ..pca_vars], scale. = TRUE)

# --- Sign Flipping (Ensure consistent directionality) ---
# Flip signs of all axes to match subsequent plotting logic
pca_result$x <- -pca_result$x
pca_result$rotation <- -pca_result$rotation


# 5. Save PCA Results
#-----------------------------------------------------------------------------
cat("Exporting PCA results...\n")

# Extract first 15 Principal Components (or fewer if N < 15)
n_pc <- min(15, ncol(pca_result$x))
pc_cols <- pca_result$x[, 1:n_pc]

# Construct output table
df_export <- cbind(
  df_pca[, .(ECO_ID, SpeciesNumber, SizeCategory, BiomeType)], 
  as.data.table(pc_cols)
)

fwrite(df_export, output_pca_data)
cat(sprintf(" -> PCA results saved to: %s\n", output_pca_data))


# 6. Generate Fig1_a: PCA Biplot
#-----------------------------------------------------------------------------
cat("Generating Fig1_a (PCA Biplot)...\n")

# Calculate variance explained
variance_explained <- pca_result$sdev^2 / sum(pca_result$sdev^2)
pc1_var <- paste0("PC1 (", round(variance_explained[1] * 100, 2), "%)")
pc2_var <- paste0("PC2 (", round(variance_explained[2] * 100, 2), "%)")

# --- 6.1 Create Base Plot Layer ---
p_biplot <- fviz_pca_biplot(
  pca_result,
  geom.ind = "point",
  pointshape = 21,
  fill.ind = df_pca$BiomeType,
  col.ind = "white",
  pointsize = df_pca$SizeCategory,
  alpha.ind = 1,
  stroke = 0.4,
  
  # Temporarily keep labels to generate layout; arrows will be redrawn
  label = "var",
  col.var = "black", 
  repel = TRUE,
  ggtheme = theme_minimal(),
) +
  scale_fill_manual(name = "Biome", values = biome_colors) +
  # Ensure legend name is Species Number
  scale_size_manual(name = "Species Number", values = c(3, 3.5, 4.5)) + 
  labs(x = pc1_var, y = pc2_var) +
  theme(
    legend.position = "right",
    panel.background = element_blank(),
    panel.border = element_rect(colour = "black", fill = NA, linewidth = 0.5),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_blank(),
    axis.ticks.length = unit(0.2, "cm"),
    axis.text = element_text(size = 11),
    legend.key = element_rect(fill = NA, color = NA)
  ) +
  guides(
    fill = guide_legend(override.aes = list(shape = 21, color = "white", size = 3)),
    size = guide_legend(override.aes = list(shape = 21, fill = "grey35", color = "white"))
  ) +
  coord_cartesian(ylim = pc2_display_range)

# --- 6.2 Extract Coordinates and Redraw Arrows ---

# Locate and extract original arrow data
arrow_layer_idx <- which(sapply(p_biplot$layers, function(x) inherits(x$geom, "GeomSegment")))
if(length(arrow_layer_idx) == 0) stop("Error: Arrow layer not found in plot object.")

plot_arrow_data <- p_biplot$layers[[arrow_layer_idx[1]]]$data

# Ensure names match
if (is.null(rownames(plot_arrow_data))) {
  plot_arrow_data$name <- rownames(pca_result$rotation)
} else {
  plot_arrow_data$name <- rownames(plot_arrow_data)
}

# Remove original arrow layer
p_biplot$layers[[arrow_layer_idx[1]]] <- NULL

# Prepare custom arrow data
# A. Original traits (Solid lines)
df_black <- data.frame(
  x_start = 0, y_start = 0,
  x_end = plot_arrow_data$x,
  y_end = plot_arrow_data$y
)

# B. Opposite traits (Dashed lines) - Invert coordinates
df_gray_source <- plot_arrow_data[plot_arrow_data$name %in% names(trait_map), ]
df_gray <- data.frame(
  x_start = 0, y_start = 0,
  x_end = -1 * df_gray_source$x, 
  y_end = -1 * df_gray_source$y,
  label = trait_map[df_gray_source$name]
)

# Add black solid arrows (Original traits)
p_biplot <- p_biplot + geom_segment(
  data = df_black,
  aes(x = x_start, y = y_start, xend = x_end, yend = y_end),
  arrow = arrow(length = arrow_tip_length), 
  color = "black",
  linewidth = line_width_custom,            
  inherit.aes = FALSE
)

# Add gray dashed arrows (Opposite traits)
# (a) Shaft (Dashed)
p_biplot <- p_biplot + geom_segment(
  data = df_gray,
  aes(x = x_start, y = y_start, xend = x_end, yend = y_end),
  arrow = NULL,            
  color = "gray45",
  linetype = dash_pattern, 
  linewidth = line_width_custom,
  inherit.aes = FALSE
)

# (b) Arrow tip (Solid segment at the end for filled appearance)
p_biplot <- p_biplot + geom_segment(
  data = df_gray,
  aes(x = x_end * 0.99, y = y_end * 0.99, xend = x_end, yend = y_end),
  arrow = arrow(length = arrow_tip_length), 
  color = "gray45",
  linetype = "solid",      
  linewidth = line_width_custom,
  inherit.aes = FALSE
)

# (c) Add opposite trait labels
p_biplot <- p_biplot + geom_text(
  data = df_gray,
  aes(x = x_end, y = y_end, label = label),
  color = "gray45",
  size = 4,
  vjust = "outward",
  hjust = "outward",
  inherit.aes = FALSE
)

# Assign to Fig1_a
Fig1_a <- p_biplot


# 7. Generate Fig1_b: Contribution Plot
#-----------------------------------------------------------------------------
cat("Generating Fig1_b (Contribution Plot)...\n")

# --- 7.1 Prepare Plotting Data ---
eig_val <- pca_result$sdev^2
var_explained_vec <- round(eig_val / sum(eig_val) * 100, 1)

pc_labels <- c(
  "PC1" = paste0("PC1 (", var_explained_vec[1], "%)"),
  "PC2" = paste0("PC2 (", var_explained_vec[2], "%)"),
  "PC3" = paste0("PC3 (", var_explained_vec[3], "%)")
)

# Extract Loadings and convert to long format
loadings_df <- as.data.frame(pca_result$rotation[, 1:3])
loadings_df$Trait <- rownames(loadings_df)

df_contrib <- loadings_df %>%
  pivot_longer(cols = c("PC1", "PC2", "PC3"), names_to = "PC", values_to = "Loading") %>%
  mutate(
    Contribution = (Loading^2) * 100,
    Direction = ifelse(Loading > 0, "Positive", "Negative")
  )

# Set factor levels to fix plotting order
df_contrib$Trait <- factor(df_contrib$Trait, levels = rev(pca_vars))
df_contrib$PC_Label <- factor(pc_labels[df_contrib$PC], levels = pc_labels)

# --- 7.2 Plotting ---
custom_contrib_colors <- c("Positive" = "#C01C71", "Negative" = "#449433")

Fig1_b <- ggplot(df_contrib, aes(x = Trait, y = Contribution, fill = Direction)) +
  geom_col(width = 0.7) +
  facet_wrap(~PC_Label, nrow = 1, scales = "free") + 
  coord_flip() +
  scale_fill_manual(values = custom_contrib_colors) +
  labs(x = NULL, y = "Contribution (%)", fill = NULL) +
  theme_classic() + 
  theme(
    axis.line = element_line(color = "black", linewidth = 0.5),
    axis.ticks = element_line(color = "black"),
    axis.ticks.length = unit(0.2, "cm"),
    axis.text = element_text(color = "black", size = 10, face = "plain"), 
    strip.text = element_text(size = 12, color = "black", face = "plain"),
    legend.text = element_text(size = 10, face = "plain"),
    axis.title = element_text(size = 11, face = "plain"),
    strip.background = element_blank(),
    panel.grid = element_blank(),
    panel.border = element_blank(),
    legend.position = "top",
    legend.key.size = unit(0.4, "cm"),
    legend.margin = margin(b = -5)
  )


# 8. Output and Save
#-----------------------------------------------------------------------------
cat("Printing and saving results...\n")

# Print to console
print(Fig1_a)
print(Fig1_b)

# Save as PDF
ggsave(output_pdf_a, plot = Fig1_a, width = 10, height = 8)
ggsave(output_pdf_b, plot = Fig1_b, width = 7, height = 8)

cat(sprintf("Fig1_a saved to: %s\n", output_pdf_a))
cat(sprintf("Fig1_b saved to: %s\n", output_pdf_b))
