#-----------------------------------------------------------------------------
# Code 15: Summarize SCM Simulation Results
#
# Description:
#   1. Iterates through SCM results for 15 traits.
#   2. Aggregates 1000 simulations per trait to calculate Mean and SD for each time bin.
#   3. Standardizes specific column names (e.g., "prop_GF_W") to generic names 
#      (e.g., "prop_State1") to ensure successful merging without NAs.
#
# Inputs:
#   - Evolution_Models_Summary.csv (To identify best model used)
#   - Flora_SCM_Simulations/{Trait}/Simulations_{Model}_1Ma/*.csv
#
# Outputs:
#   - Evolution_SCM_Summary.csv
#-----------------------------------------------------------------------------

# 1. Global Settings and Libraries
#-----------------------------------------------------------------------------
setwd("F:/GitHub/ZhangChunyu-GeoBio/Angiosperm-Biogeographical-Spectrum/Data")

if (!requireNamespace("dplyr", quietly = TRUE)) install.packages("dplyr")
if (!requireNamespace("stringr", quietly = TRUE)) install.packages("stringr")

library(dplyr)
library(stringr)

# 2. Paths and Parameters
#-----------------------------------------------------------------------------
scm_base_dir <- "Flora_SCM_Simulations"
summary_file <- "Evolution_Models_Summary.csv" 
output_summary_file <- "Evolution_SCM_Summary.csv"

# List of 15 Traits
traits_list <- c("GF", "LC", "PH", "RS", "PT", "LS", "LM", "LV", 
                 "SS", "IF", "OP", "FS", "PF", "FT", "FD")

# Trait Definition Dictionary (State 1 = Ancestral/Background, State 2 = Derived/Target)
TRAIT_DEFINITIONS <- list(
  "GF" = c("GF_W", "GF_H"), "LC" = c("LC_P", "LC_A"), "PH" = c("PH_E", "PH_D"),
  "RS" = c("RS_T", "RS_F"), "PT" = c("PT_U", "PT_M"), "LS" = c("LS_S", "LS_C"),
  "LM" = c("LM_E", "LM_L"), "LV" = c("LV_R", "LV_P"), "SS" = c("SS_B", "SS_U"),
  "IF" = c("IF_D", "IF_I"), "OP" = c("OP_H", "OP_E"), "FS" = c("FS_A", "FS_Z"),
  "PF" = c("PF_C", "PF_S"), "FT" = c("FT_D", "FT_F"), "FD" = c("FD_D", "FD_I")
)

# Check Dependencies
if (!file.exists(summary_file)) stop("Error: Evolution_Models_Summary.csv not found.")
model_summary <- read.csv(summary_file, stringsAsFactors = FALSE)

# 3. Main Processing Loop
#-----------------------------------------------------------------------------
final_summary_list <- list()

cat("Starting SCM Result Aggregation (Standardized Version)...\n")

for (tr in traits_list) {
  
  cat(paste0("\n--- Processing Trait: ", tr, " ---\n"))
  
  # 3.1 Get Model Information
  best_model_info <- model_summary %>% filter(Trait == tr)
  if (nrow(best_model_info) == 0) {
    warning(paste("Model info not found for trait", tr, "- Skipping."))
    next
  }
  best_model <- best_model_info$Model[1]
  
  # Construct Path
  sim_dir <- file.path(scm_base_dir, tr, paste0("Simulations_", best_model, "_1Ma"))
  if (!dir.exists(sim_dir)) {
    warning(paste("Directory not found:", sim_dir, "- Skipping."))
    next
  }
  
  # 3.2 Read Simulation Files
  sim_files <- list.files(sim_dir, pattern = "^scm_sim_.*\\.csv$", full.names = TRUE)
  if (length(sim_files) == 0) {
    warning("No simulation files found - Skipping.")
    next
  }
  
  cat(sprintf("Reading %d files...\n", length(sim_files)))
  
  # Read and bind all simulations
  all_sims_list <- lapply(sim_files, function(f) {
    # Extract seed from filename for tracking (optional)
    seed_num <- as.integer(str_extract(basename(f), "(?<=seed_)\\d+"))
    df <- read.csv(f, stringsAsFactors = FALSE)
    df$seed <- seed_num
    return(df)
  })
  
  all_sims_df <- do.call(rbind, all_sims_list)
  if (is.null(all_sims_df) || nrow(all_sims_df) == 0) next
  
  # Clean column names (remove BOM artifacts if present)
  colnames(all_sims_df) <- gsub("^X\\.|^ï\\.\\.", "", colnames(all_sims_df))
  
  # 3.3 Calculate Statistics (Detailed Version)
  cat("Calculating Mean and SD...\n")
  
  # Group by time bin and calculate stats
  detailed_stats <- all_sims_df %>%
    group_by(bin_id, bin_start_age, bin_end_age) %>%
    summarise(
      n_sims = n(), 
      across(
        .cols = where(is.numeric) & -any_of(c("seed", "bin_id", "bin_start_age", "bin_end_age")),
        .fns = list(mean = mean, sd = sd),
        .names = "{.col}_{.fn}"
      ),
      .groups = "drop"
    ) %>%
    arrange(bin_id)
  
  # Save Detailed Stats (Preserving original state names)
  detailed_output_path <- file.path(scm_base_dir, tr, "SCM_Aggregate_Statistics.csv")
  write.csv(detailed_stats, detailed_output_path, row.names = FALSE)
  
  # 3.4 Standardize Column Names
  cat("Standardizing columns for master summary...\n")
  
  s1_name <- TRAIT_DEFINITIONS[[tr]][1] # e.g., "GF_W"
  s2_name <- TRAIT_DEFINITIONS[[tr]][2] # e.g., "GF_H"
  
  # Define Specific Column Names (Generated by summarise)
  cols_specific <- c(
    paste0("prop_", s1_name, "_mean"), paste0("prop_", s1_name, "_sd"),
    paste0("prop_", s2_name, "_mean"), paste0("prop_", s2_name, "_sd"),
    paste0("rate_", s1_name, "_to_", s2_name, "_mean"), paste0("rate_", s1_name, "_to_", s2_name, "_sd"),
    paste0("rate_", s2_name, "_to_", s1_name, "_mean"), paste0("rate_", s2_name, "_to_", s1_name, "_sd")
  )
  
  # Define Generic Column Names (Target)
  cols_generic <- c(
    "prop_State1_mean", "prop_State1_sd",
    "prop_State2_mean", "prop_State2_sd",
    "rate_1to2_mean",   "rate_1to2_sd",
    "rate_2to1_mean",   "rate_2to1_sd"
  )
  
  # Check if columns exist
  if (all(cols_specific %in% colnames(detailed_stats))) {
    
    # Extract Base Columns
    temp_df <- detailed_stats %>% select(bin_id, bin_start_age, bin_end_age, n_sims)
    
    # Extract Data Columns
    data_df <- detailed_stats %>% select(all_of(cols_specific))
    
    # Rename Data Columns
    colnames(data_df) <- cols_generic
    
    # Bind and Add Metadata
    summary_standardized <- cbind(temp_df, data_df)
    summary_standardized$Trait <- tr
    summary_standardized$State1_Label <- s1_name
    summary_standardized$State2_Label <- s2_name
    
    # Store in List
    final_summary_list[[tr]] <- summary_standardized
    
  } else {
    warning(paste("Trait", tr, "missing expected columns. Simulation data might be incomplete."))
  }
}

# 4. Generate Master Summary
#-----------------------------------------------------------------------------
if (length(final_summary_list) > 0) {
  
  cat("\nMerging all traits into master file...\n")
  
  # Bind rows and reorder columns
  final_df <- bind_rows(final_summary_list) %>%
    select(Trait, State1_Label, State2_Label, 
           bin_id, bin_start_age, bin_end_age, n_sims,
           prop_State1_mean, prop_State1_sd,
           prop_State2_mean, prop_State2_sd,
           rate_1to2_mean, rate_1to2_sd,
           rate_2to1_mean, rate_2to1_sd)
  
  # Save to CSV
  write.csv(final_df, output_summary_file, row.names = FALSE)
  
  cat("=======================================================\n")
  cat(sprintf("Master Summary Saved: %s\n", file.path(getwd(), output_summary_file)))
  cat("Note: All traits are aligned. No NAs in data columns.\n")
  cat("Legend: State 1 = Ancestral, State 2 = Derived.\n")
  cat("=======================================================\n")
  print(head(final_df))
  
} else {
  warning("Error: No valid data generated for final summary.")
}
